SELECT 
    SUM(G.SCORE) AS SCORE,
    E.EMP_NO AS EMP_NO,
    E.EMP_NAME AS EMP_NAME,
    E.POSITION AS POSITION,
    E.EMAIL AS EMAIL
FROM HR_GRADE G
JOIN HR_EMPLOYEES E
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;