SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR, 
    M.MAX_COLONY - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID AS ID
FROM ECOLI_DATA E
JOIN (
    SELECT 
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) M
ON M.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV;