SELECT 
    COUNT(I.FISH_TYPE) AS FISH_COUNT,
    MAX(I.LENGTH) AS MAX_LENGTH,
    I.FISH_TYPE AS FISH_TYPE
FROM FISH_INFO I
GROUP BY FISH_TYPE
HAVING AVG(IF(IFNULL(LENGTH, 0) < 10, 10, LENGTH)) >= 33
ORDER BY FISH_TYPE;
