SELECT 
    COUNT(I.FISH_TYPE) AS FISH_COUNT,
    MAX(I.LENGTH) AS MAX_LENGTH,
    I.FISH_TYPE AS FISH_TYPE
FROM FISH_INFO I
GROUP BY FISH_TYPE
HAVING AVG(
    CASE
        WHEN LENGTH < 10 THEN 10
        WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH
    END
) >= 33
ORDER BY FISH_TYPE;