SELECT 
    I.ID AS ID, 
    N.FISH_NAME AS FISH_NAME, 
    I.LENGTH AS LENGTH
FROM FISH_INFO I 

JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) M
ON M.FISH_TYPE = I.FISH_TYPE AND M.MAX_LENGTH = I.LENGTH

JOIN FISH_NAME_INFO N
ON N.FISH_TYPE = I.FISH_TYPE;