SELECT 
    U.USER_ID AS USER_ID,
    U.NICKNAME AS NICKNAME,
    SUM(G.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD G
JOIN USED_GOODS_USER U
ON U.USER_ID = G.WRITER_ID
WHERE G.STATUS LIKE 'DONE'
GROUP BY U.USER_ID
HAVING SUM(G.PRICE) >= 700000
ORDER BY TOTAL_SALES;